language: php
php:
  - '7.3.8'

jobs:
  include:
    - stage: install libraries
      script: make install
    - stage: linter tests
      script: make lint
    - stage: unit tests
      script: make test
